version: "3.9"
services:
  redis:
    container_name: "dev-blog-redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
  database:
    container_name: "dev-blog-db"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=p@ssw0rd
