DROP PROCEDURE IF EXISTS [dbo].GetPostsByHandle;
DROP PROCEDURE IF EXISTS [dbo].GetPostsByUserId;
DROP PROCEDURE IF EXISTS [dbo].GetBlogBySlug;
DROP PROCEDURE IF EXISTS [dbo].GetBlogsByUserId;
DROP TABLE IF EXISTS [dbo].posts;
DROP TABLE IF EXISTS [dbo].blogs;
DROP TABLE IF EXISTS [dbo].users;
